title: CSS Bristol
email: webmaster@cssbristol.co.uk
description: > # Computer Science Society of the University of Bristol. We organise events and promote job offers for our members and students.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.cssbristol.co.uk" # the base hostname & protocol for your site
twitter_username: cssbristol
github_username: cssbristol

# Build settings
markdown: kramdown

collections:
  tutorials:
    output: true
    permalink: /tutorials/:path/
